/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Login Service API
 * Ecosystem The System Guys API Document
 * OpenAPI spec version: 1.0
 */

import axios from 'axios'
import type { AxiosRequestConfig, AxiosResponse } from 'axios'
import type {
  UsermodelLoginUserRequest,
  UsermodelLoginUserResponse,
  UsermodelUserCreate,
  UsermodelUserResponse,
} from '../model'

/**
 * login user, returns user and set session
 * @summary Login new user
 */
export const postAuthLogin = (
  usermodelLoginUserRequest: UsermodelLoginUserRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UsermodelLoginUserResponse>> => {
  return axios.post(
    `http://localhost:8080/v1/auth/login`,
    usermodelLoginUserRequest,
    options,
  )
}

/**
 * Register new user
 * @summary Register new user
 */
export const postAuthRegister = (
  usermodelUserCreate: UsermodelUserCreate,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UsermodelUserResponse>> => {
  return axios.post(
    `http://localhost:8080/v1/auth/register`,
    usermodelUserCreate,
    options,
  )
}
