/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Login Service API
 * Ecosystem Hallucination Guys API Document
 * OpenAPI spec version: 1.0
 */

export interface CommonAppError {
  error_key?: string
  log?: string
  message?: string
  status_code?: number
}
