/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Login Service API
 * Ecosystem The System Guys API Document
 * OpenAPI spec version: 1.0
 */

export interface RequestSignUpRequest {
  email?: string
  name?: string
  password?: string
  passwordConfirm?: string
  photo?: string
}
