/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Login Service API
 * Ecosystem The System Guys API Document
 * OpenAPI spec version: 1.0
 */
import type { UsermodelUserResponse } from './usermodelUserResponse'

export interface UsermodelLoginUserResponse {
  access_token?: string
  access_token_expires_at?: string
  user?: UsermodelUserResponse
}
