/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Login Service API
 * Ecosystem The System Guys API Document
 * OpenAPI spec version: 1.0
 */
import type { UsermodelUserRole } from './usermodelUserRole'

export interface UsermodelUserCreate {
  created_at?: string
  email?: string
  first_name?: string
  last_name?: string
  password?: string
  phone?: string
  role?: UsermodelUserRole
  status?: number
  updated_at?: string
}
