/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Login Service API
 * Ecosystem Hallucination Guys API Document
 * OpenAPI spec version: 1.0
 */

export type UsermodelUserRole =
  (typeof UsermodelUserRole)[keyof typeof UsermodelUserRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsermodelUserRole = {
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const
