/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * Login Service API
 * Ecosystem Hallucination Guys API Document
 * OpenAPI spec version: 1.0
 */

export interface UsermodelLoginUserResponse {
  access_token?: string
  email?: string
  expired_at?: string
}
